# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'tools.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat_mean.npy'
user_graph_dict_file: 'user_graph_dict.npy'

field_separator: "\t"

train_batch_size: 12288
eval_batch_size: 12288

metrics: ["Recall", "NDCG"]
topk: [10, 20]